public enum GameSceneId
{
    SPLASH = 0,
    STORY_BOARD = 1,
    TUTORIAL_OR_GAME_NAVIGATOR = 2,
    MENU = 3,
    TUTORIAL1_STORY_LINE = 4,
    TUTORIAL2_STORY_LINE = 5,
    TUTORIAL3_STORY_LINE = 6,
    SCORE_BREAKDOWN = 7,
    GAME_SCENE = 8,
    SCORE = 9,
}
